version = 1

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = [
    "react",
    "angularjs"
  ]
  environment = [
    "nodejs",
    "mongo",
    "jquery",
    "browser"
  ]
  dialect = "typescript"
